package metodist.entity;
// Generated 14.10.2019 8:27:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Courses generated by hbm2java
 */
public class Courses  implements java.io.Serializable {


     private Integer idCourses;
     private String title;
     private String organization;
     private Teachercourses teachercourses;
     private Set teachers = new HashSet(0);

    public Courses() {
    }

    public Courses(String title, String organization, Teachercourses teachercourses, Set teachers) {
       this.title = title;
       this.organization = organization;
       this.teachercourses = teachercourses;
       this.teachers = teachers;
    }
   
    public Integer getIdCourses() {
        return this.idCourses;
    }
    
    public void setIdCourses(Integer idCourses) {
        this.idCourses = idCourses;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(String organization) {
        this.organization = organization;
    }
    public Teachercourses getTeachercourses() {
        return this.teachercourses;
    }
    
    public void setTeachercourses(Teachercourses teachercourses) {
        this.teachercourses = teachercourses;
    }
    public Set getTeachers() {
        return this.teachers;
    }
    
    public void setTeachers(Set teachers) {
        this.teachers = teachers;
    }




}


