package metodist.entity;
// Generated 14.10.2019 8:27:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private Integer idEvent;
     private String title;
     private Set documents = new HashSet(0);

    public Event() {
    }

    public Event(String title, Set documents) {
       this.title = title;
       this.documents = documents;
    }
   
    public Integer getIdEvent() {
        return this.idEvent;
    }
    
    public void setIdEvent(Integer idEvent) {
        this.idEvent = idEvent;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Set getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Set documents) {
        this.documents = documents;
    }




}


