package metodist.entity;
// Generated 14.10.2019 8:27:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Teacher generated by hbm2java
 */
public class Teacher  implements java.io.Serializable {


     private Integer idTeacher;
     private Courses courses;
     private String fioTeacher;
     private Date dateOfAttestation;
     private Date dateBeginCourses;
     private Date dateEndCourses;
     private String category;
     private String nameOfCourses;
     private Set documents = new HashSet(0);
     private Set teachercourseses = new HashSet(0);

    public Teacher() {
    }

    public Teacher(Courses courses, String fioTeacher, Date dateOfAttestation, Date dateBeginCourses, Date dateEndCourses, String category, String nameOfCourses, Set documents, Set teachercourseses) {
       this.courses = courses;
       this.fioTeacher = fioTeacher;
       this.dateOfAttestation = dateOfAttestation;
       this.dateBeginCourses = dateBeginCourses;
       this.dateEndCourses = dateEndCourses;
       this.category = category;
       this.nameOfCourses = nameOfCourses;
       this.documents = documents;
       this.teachercourseses = teachercourseses;
    }
   
    public Integer getIdTeacher() {
        return this.idTeacher;
    }
    
    public void setIdTeacher(Integer idTeacher) {
        this.idTeacher = idTeacher;
    }
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }
    public String getFioTeacher() {
        return this.fioTeacher;
    }
    
    public void setFioTeacher(String fioTeacher) {
        this.fioTeacher = fioTeacher;
    }
    public Date getDateOfAttestation() {
        return this.dateOfAttestation;
    }
    
    public void setDateOfAttestation(Date dateOfAttestation) {
        this.dateOfAttestation = dateOfAttestation;
    }
    public Date getDateBeginCourses() {
        return this.dateBeginCourses;
    }
    
    public void setDateBeginCourses(Date dateBeginCourses) {
        this.dateBeginCourses = dateBeginCourses;
    }
    public Date getDateEndCourses() {
        return this.dateEndCourses;
    }
    
    public void setDateEndCourses(Date dateEndCourses) {
        this.dateEndCourses = dateEndCourses;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getNameOfCourses() {
        return this.nameOfCourses;
    }
    
    public void setNameOfCourses(String nameOfCourses) {
        this.nameOfCourses = nameOfCourses;
    }
    public Set getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Set documents) {
        this.documents = documents;
    }
    public Set getTeachercourseses() {
        return this.teachercourseses;
    }
    
    public void setTeachercourseses(Set teachercourseses) {
        this.teachercourseses = teachercourseses;
    }




}


