package meth.entity;
// Generated 14.10.2019 9:59:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Document generated by hbm2java
 */
public class Document  implements java.io.Serializable {


     private Integer idDocument;
     private Event event;
     private Teacher teacher;
     private String titleOfDocument;
     private String path;
     private Date dateDownload;
     private String studentInfo;
     private String groupStudents;
     private String lieu;
     private String titleOfFile;

    public Document() {
    }

    public Document(Event event, Teacher teacher, String titleOfDocument, String path, Date dateDownload, String studentInfo, String groupStudents, String lieu, String titleOfFile) {
       this.event = event;
       this.teacher = teacher;
       this.titleOfDocument = titleOfDocument;
       this.path = path;
       this.dateDownload = dateDownload;
       this.studentInfo = studentInfo;
       this.groupStudents = groupStudents;
       this.lieu = lieu;
       this.titleOfFile = titleOfFile;
    }
   
    public Integer getIdDocument() {
        return this.idDocument;
    }
    
    public void setIdDocument(Integer idDocument) {
        this.idDocument = idDocument;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
    public String getTitleOfDocument() {
        return this.titleOfDocument;
    }
    
    public void setTitleOfDocument(String titleOfDocument) {
        this.titleOfDocument = titleOfDocument;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public Date getDateDownload() {
        return this.dateDownload;
    }
    
    public void setDateDownload(Date dateDownload) {
        this.dateDownload = dateDownload;
    }
    public String getStudentInfo() {
        return this.studentInfo;
    }
    
    public void setStudentInfo(String studentInfo) {
        this.studentInfo = studentInfo;
    }
    public String getGroupStudents() {
        return this.groupStudents;
    }
    
    public void setGroupStudents(String groupStudents) {
        this.groupStudents = groupStudents;
    }
    public String getLieu() {
        return this.lieu;
    }
    
    public void setLieu(String lieu) {
        this.lieu = lieu;
    }
    public String getTitleOfFile() {
        return this.titleOfFile;
    }
    
    public void setTitleOfFile(String titleOfFile) {
        this.titleOfFile = titleOfFile;
    }




}


