package meth.entity;
// Generated 14.10.2019 9:59:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Teachercourses generated by hbm2java
 */
public class Teachercourses  implements java.io.Serializable {


     private int idCourses;
     private Courses courses;
     private Teacher teacher;
     private String nameOfCourses;
     private String fioTeacher;
     private Date dateOfBegin;
     private Date dateOfEnd;
     private String spentTime;

    public Teachercourses() {
    }

	
    public Teachercourses(Courses courses) {
        this.courses = courses;
    }
    public Teachercourses(Courses courses, Teacher teacher, String nameOfCourses, String fioTeacher, Date dateOfBegin, Date dateOfEnd, String spentTime) {
       this.courses = courses;
       this.teacher = teacher;
       this.nameOfCourses = nameOfCourses;
       this.fioTeacher = fioTeacher;
       this.dateOfBegin = dateOfBegin;
       this.dateOfEnd = dateOfEnd;
       this.spentTime = spentTime;
    }
   
    public int getIdCourses() {
        return this.idCourses;
    }
    
    public void setIdCourses(int idCourses) {
        this.idCourses = idCourses;
    }
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
    public String getNameOfCourses() {
        return this.nameOfCourses;
    }
    
    public void setNameOfCourses(String nameOfCourses) {
        this.nameOfCourses = nameOfCourses;
    }
    public String getFioTeacher() {
        return this.fioTeacher;
    }
    
    public void setFioTeacher(String fioTeacher) {
        this.fioTeacher = fioTeacher;
    }
    public Date getDateOfBegin() {
        return this.dateOfBegin;
    }
    
    public void setDateOfBegin(Date dateOfBegin) {
        this.dateOfBegin = dateOfBegin;
    }
    public Date getDateOfEnd() {
        return this.dateOfEnd;
    }
    
    public void setDateOfEnd(Date dateOfEnd) {
        this.dateOfEnd = dateOfEnd;
    }
    public String getSpentTime() {
        return this.spentTime;
    }
    
    public void setSpentTime(String spentTime) {
        this.spentTime = spentTime;
    }




}


